version: '3.4'

services:
  webapi:
    image: ssiljk/exch-webapi:exch-webapi
 
    ports:
            - "5000:80"
    depends_on:
      - db
  db:
    image: ssiljk/exch-db:exch-db
    
    # ports:
    #   - "1444:1433"
    volumes:
     - mssqldata:/var/opt/mssql

volumes:
  mssqldata: