version: '3.4'
# con este se arrancan los dos containers del backend
services:
  exchange.api:
    image: exchangeapi2:dev
    environment:
         - ASPNETCORE_ENVIRONMENT=Staging
         - ASPNETCORE_URLS=https://+:443;http://+:80
         - ASPNETCORE_Kestrel__Certificates__Default__Password=xpassword
         - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
            - "5000:80"
            - "5001:443"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
  db:
    image: exch-db:dev
    
    #ports:
    #  - "1444:1433"
    volumes:
     - mssqldata:/var/opt/mssql

volumes:
  mssqldata: